config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :plays do
    resources :reviews
  end
  root "plays#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :play_img
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    if params[:category].blank?
      @plays=Play.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @play.reviews.blank?
      @average_review=0
    else
      @average_review=@play.reviews.average(:rating).round(2)
    end
  end

  def new
    @play=current_user.plays.build
    @categories=Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @play=current_user.plays.build(play_params)
    @play.category_id=params[:category_id]
    @play.play_img.attach(params[:play][:play_img])
    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories=Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @play.category_id=params[:category_id]
    @play.play_img.attach(params[:play][:play_img])

    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private
  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id)
  end
  def find_play
    @play=Play.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def new
    @review=Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private
  def find_play
    @play=Play.find(params[:play_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Broadway
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js'
    = javascript_include_tag '/assets/jquery.raty'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          .navbar-brand= link_to 'Broadway', root_path
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Join', new_user_registration_path
            %li= link_to 'Sign In', new_user_session_path
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "area-expanded" => "false"}
              Genres
              %span.caret
            %ul.dropdown-menu{"role" => "menu"}
              - Category.all.each do |category|
                %li{ :class => ("active" if params[:category] == category.name?) }
                  = link_to category.name, plays_path(category: category.name), class: "link"
          - if user_signed_in?
            %li= link_to 'Add Play', new_play_path
    .container
      - flash.each do |name,msg|
        = content_tag :div, msg, class: 'alert alert-info'

      = yield

app/views/plays/_form.html.haml
= simple_form_for @play do |f|
  -if @play.errors.any?
    %h2= pluralize(@play.errors.count,"error")
    Prevented this Play from saving
    %ul
      @play.errors.full_messages.each do |msg|
      %li= msg

  .form-group
    = f.file_field :play_img
  .form-group
    = select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category")
  .form-group
    = f.input :title, label: "Play Title", input_html: {class: 'form-control'}
  .form-group
    = f.input :description, input_html: {class: 'form-control'}
  .form-group
    = f.input :director, input_html: {class: 'form-control'}

  = f.button :submit, class: 'btn btn-primary'

app/views/plays/edit.html.haml
.col-md-10.col-md-offset-1
  .new-play-form
    %h1 Edit Broadway Play

    = simple_form_for @play, html: {multipart: true} do |f|
      -if @play.errors.any?
        %h2= pluralize(@play.errors.count,"error")
        Prevented this Play from saving
        %ul
          @play.errors.full_messages.each do |msg|
          %li= msg
      .form-group
        = f.file_field :play_img
      .form-group
        = f.select :category_id, @categories
      .form-group
        = f.input :title, label: "Play Title", input_html: {class: 'form-control'}
      .form-group
        = f.input :description, input_html: {class: 'form-control'}
      .form-group
        = f.input :director, input_html: {class: 'form-control'}

      = f.button :submit, class: 'btn btn-primary'

app/views/plays/index.html.haml
%h1.current-category= params[:category]

- if @plays.count ==0
  %h3 There are no Plays in this Category
- else
  .row
    - @plays.each do |play|
      .col-md-3
        %a{:href => "/plays/#{play.id}"}
          = image_tag play.play_img.variant(resize: "250x350>"), class: 'play'

app/views/plays/new.html.haml
.col-md-10.col-md-offset-1
  .new-play-form
    %h1 New Broadway Play
    = render "form"

app/views/plays/show.html.haml
.row
  .col-md-4
    = image_tag @play.play_img.variant(resize: "325x475>"), class: 'play-show'
  .col-md-8
    .play-info
      %h2.play-title= @play.title
      %h3.play-director
        %span
          %em From:
        = @play.director
      %h4.play-director= @play.category.name
      %h4.avg-rating Rating
      %div.average-review-rating{ "data-score" => "#{@average_review}" }
      %span.number-of-reviews
        %em From:
      = @play.reviews.count
      reviewers
      %p.play-desc= @play.description
      .links.btn-group
        - if user_signed_in?
          - if @play.user_id == current_user.id
            = link_to "Edit", edit_play_path(@play), class: "btn btn-custom"
            = link_to "Delete", play_path(@play), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-custom"

.row
  .col-md-12
    .reviews
      %h1 Reviews
      = render @play.reviews
      %div
        = link_to 'Add Reviews', new_play_review_path(@play), class: 'btn-custom'

:javascript
  $(document).ready(function() {
    $(".review-rating").raty({
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      },
      path: '/assets/'
    });

    $(".average-review-rating").raty({
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
        },
      path: '/assets/'
    });
  });

app/views/reviews/_form.html.haml
= simple_form_for ([@play, @play.reviews.build]) do |f|
  #rating-form
    %label Rating
  = f.input :comment
  = f.button :submit, class: "btn-custom2"

:javascript
  $(document).ready(function() {
    $("#rating-form").raty({
      path: '/assets/',
      scoreName: 'review[rating]'
    });
  });

app/views/reviews/_review.html.haml
.review
  %div.review-rating{ "data-score" => "#{review.rating}" }
  %p.review-comment= review.comment

  - if user_signed_in?
    - if review.user_id == current_user.id
      .links.btn-group
        = link_to "Edit", edit_play_review_path(review.play, review), class: "btn btn-custom"
        = link_to "Delete", play_review_path(review.play, review), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-custom"

app/views/reviews/edit.html.haml
.col-md-10.col-md-offset-1
  .edit-review-form
    %h1 Edit Review
    = simple_form_for ([@play, @review]) do |f|
      %label Rating
      %div#rating-form{ "data-score" => "#{@review.rating}"}
      = f.input :comment
      = f.button :submit, class: "btn-custom2"

:javascript
  $(document).ready(function() {
    $("#rating-form").raty({
      score: function() {
        return $(this).attr('data-score');
        },
      path: '/assets/',
      scoreName: 'review[rating]'
    });
  });

app/views/reviews/new.html.haml
.col-md-10.col-md-offset-1
  .new-review-form
    %h1 Post Review
    = render 'form'